services:
  auth-service-db:
    image: postgres:18-alpine
    container_name: auth_service_postgres
    environment:
      - POSTGRES_DB=${AUTH_SERVICE_DB_NAME}
      - POSTGRES_USER=${AUTH_SERVICE_DB_USERNAME}
      - POSTGRES_PASSWORD=${AUTH_SERVICE_DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${AUTH_SERVICE_DB_PORT}:5432"
    volumes:
      - auth_service_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  core-auth-service:
    image: ghcr.io/yuryshakhau1/core-auth-service:latest
    container_name: core_auth_service
    profiles:
      - docker
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    environment:
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
      - AUTH_SERVICE_DB_NAME=${AUTH_SERVICE_DB_NAME}
      - AUTH_SERVICE_DB_USERNAME=${AUTH_SERVICE_DB_USERNAME}
      - AUTH_SERVICE_DB_PASSWORD=${AUTH_SERVICE_DB_PASSWORD}
      - AUTH_SERVICE_DB_PORT=${AUTH_SERVICE_DB_PORT}
      - KAFKA_HOST_PORT=${KAFKA_HOST_PORT}
      - CARD_SECRET_KEY=${CARD_SECRET_KEY}
      - REDIS_SECRET_PASSWORD=${REDIS_SECRET_PASSWORD}
    depends_on:
      - auth-service-db

volumes:
  auth_service_postgres_data:
